In [2]:
# 1.1: Create a list: nums= [3,5,7,8,12] make another named 'cubes' and append the cubes of the given list 'nums' in this list and print it

nums = [3, 5, 7, 8, 12]
cubes = []
for num in nums:
  cubes.append(num ** 3)
print(cubes)


[27, 125, 343, 512, 1728]


In [4]:
# 1.2: Create an empty dictionary: dict = {}, add the following data to the dictionary: ‘parrot’: 2, ‘goat’: 4, ‘spider’: 8, ‘crab’:
# 10 as key value pairs.

dict = {}
dict['parrot'] = 2
dict['goat'] = 4
dict['spider'] = 8
dict['crab'] = 10


In [5]:
# 1.3: Use the ‘items’ method to loop over the dictionary (dict) and print the animals and their corresponding legs. Sum
# the legs of each animal, and print the total at the end.

total_legs = 0
for animal, legs in dict.items():
  print(f"{animal} has {legs} legs.")
  total_legs += legs

print(f"Total legs: {total_legs}")


parrot has 2 legs.
goat has 4 legs.
spider has 8 legs.
crab has 10 legs.
Total legs: 24


In [6]:
# 1.4: Create a tuple: A = (3, 9, 4, [5, 6]), change the value in the list from ‘5’ to ‘8’.

A = (3, 9, 4, [5, 6])
A[3][0] = 8
print(A)



(3, 9, 4, [8, 6])


In [9]:
# 1.5: Delete the tuple A.

A = (3, 9, 4, [5, 6])
A[3][0] = 8
print(A)

del A



(3, 9, 4, [8, 6])


In [10]:
# 1.6: Create another tuple: B = (‘a’, ‘p’, ‘p’, ‘l’, ‘e’), print the number of occurrences of ‘p’ in the tuple.

B = ('a', 'p', 'p', 'l', 'e')
print(B.count('p'))


2


In [11]:
# 1.7: Print the index of ‘l’ in the tuple.

B = ('a', 'p', 'p', 'l', 'e')
print(B.index('l'))


3


In [26]:
import numpy as np

# 2.1 Convert matrix A into numpy array
# Original matrix A
matrix_A = [[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]]

A = np.array(matrix_A)
print("Original matrix A (as a list of lists):\n", matrix_A)
print("\nConverted numpy array A:\n", A)

2.1: Original matrix A (as a list of lists):
 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Converted numpy array A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 2.2 Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2

b = A[:2, :2]

print("\nSubarray b (first 2 rows and columns 1 and 2):\n", b)

In [ ]:
# 2.3 Create an empty matrix ‘C’ with the same shape as ‘A’

C = np.empty_like(A)

print("\nEmpty Matrix",C)

In [ ]:
# 2.4 Add the vector z to each column of the matrix ‘A’ with an explicit loop and store it in ‘C’

z = np.array([1, 0, 1])

for i in range(A.shape[1]):  # iterate over columns
    C[:, i] = A[:, i] + z
    print("\nVector Z added:",C)


In [ ]:
# 2.5 Add and print the matrices X and Y

X = np.array([[1, 2],
              [3, 4]])
Y = np.array([[5, 6],
              [7, 8]])

sum_X_Y = X + Y
print("\nSum of X and Y:\n", sum_X_Y)


In [ ]:
# 2.6 Multiply and print the matrices X and Y

product_X_Y = np.dot(X, Y)

print("\nProduct of X and Y:\n", product_X_Y)

In [ ]:
# 2.7 Compute and print the element-wise square root of matrix Y

sqrt_Y = np.sqrt(Y)

print("\nElement-wise square root of Y:\n", sqrt_Y)


In [ ]:
# 2.8 Compute and print the dot product of the matrix X and vector v

v = np.array([9, 10])

dot_X_v = np.dot(X, v)

print("\nDot product of X and v:\n", dot_X_v)

In [ ]:
# 2.9 Compute and print the sum of each column of X

sum_columns_X = np.sum(X, axis=0)

print("\nSum of each column of X:\n", sum_columns_X)


In [19]:
# 3.1 Create a function ‘Compute’ that takes two arguments, distance and time, and use it to calculate velocity. and print it

def Compute(distance, time):
  if time == 0:
    return "Time cannot be zero."
  else:
    velocity = distance / time
    return velocity

#for example:
distance = 100
time = 2

velocity = Compute(distance, time)
print(f"Velocity: {velocity}")


Velocity: 50.0


In [9]:
# 3.2 Make a list named ‘even_num’ that contains all even numbers up till 12. Create a function ‘mult’ that takes the list
# ‘even_num’ as an argument and calculates the products of all entries using a for loop.

def mult(even_num):

  product = 1
  for num in even_num:
    product *= num
  return product

# Create the list of even numbers
even_num = [x for x in range(2, 13, 2)]
print("\nEven Numbers:",even_num)

# Calculate the product of all entries
result = mult(even_num)
print(f"The product of all even numbers up to 12 is: {result}")



Even Numbers: [2, 4, 6, 8, 10, 12]
The product of all even numbers up to 12 is: 46080


In [13]:
# Task 4: Create Panda DataFrame
import pandas as pd

# Creating a DataFrame with the given data
data = {'C1': [1, 2, 3, 5, 5],
        'C2': [6, 7, 5, 4, 8],
        'C3': [7, 9, 8, 6, 5],
        'C4': [7, 5, 2, 8, 8]}

# Creating the dataframe
df = pd.DataFrame(data)

# Displaying the dataframe
print("DataFrame 'pd':\n", df)


DataFrame 'pd':
    C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [14]:
# 4.1: Print only the first two rows of the dataframe.

print(df.head(2))


   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [16]:
# 4.2: Print the second column.

print(df.columns)
print(df["C2"])

Index(['C1', 'C2', 'C3', 'C4'], dtype='object')
0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [17]:
# 4.3: Change the name of the third column from ‘C3’ to ‘B3’.

df = df.rename(columns={'C3': 'B3'})
print(df)


   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [18]:
# 4.4: Add a new column to the dataframe and name it ‘Sum’.

df['Sum'] = df.sum(axis=1)
print(df)


   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [19]:
# 4.5: Sum the entries of each row and add the result in the column ‘Sum’.

df['Sum'] = df.sum(axis=1)
print(df)


   C1  C2  B3  C4  Sum
0   1   6   7   7   42
1   2   7   9   5   46
2   3   5   8   2   36
3   5   4   6   8   46
4   5   8   5   8   52


In [1]:
# 4.6: Read CSV file named ‘hello_sample.csv’ (the file is available in the class Google Drive shared folder) into a Pandas dataframe.

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/hello_sample.csv')
print(df)


    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
# 4.7: Print complete dataframe.

print(df)


    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [4]:
# 4.8: Print only bottom 2 records of the dataframe.

print(df.tail(2))


   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [5]:
# 4.9: Print information about the dataframe.

print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 864.0+ bytes
None


In [6]:
# 4.10: Print shape (rows x columns) of the dataframe.

print(df.shape)


(23, 4)


In [7]:
# 4.11: Sort the data of the dataFrame using column ‘Weight’.

# Assuming 'df' is your DataFrame and 'Weight' is the column name
df_sorted = df.sort_values(by='Weight')
print(df_sorted)


    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [8]:
# 4.12: Use isnull() and dropna() methods of the Pandas dataframe and see if they produce any changes.

# Check for null values
print(df.isnull())

# Drop rows with null values
df_dropped = df.dropna()
print(df_dropped)


    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False
    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March 